pipeline {
    
    agent any
    parameters {
        string(name: 'SOLUTION_PATH', defaultValue: 'WebApi/WebApi.sln', description: 'Path to the Solution')
        choice(name: "Environment", choices: ["build"],description : 'Select Environment to run')
    }
    stages {
        
          stage('build') {
            when {
                expression {
                  params.Environment == 'build';
                }
            }
            steps {
                echo "----------------------Building Started-------------------"
                powershell '''echo $ENV:WORKSPACE '''
            }
         }
        }
    }
        

