pipeline {
    
    agent any
    parameters {
        string(name: 'SOLUTION_PATH', defaultValue: 'WebApi/WebApi.sln', description: 'Path to the Solution')
        string(name: 'TEST_PROJECT_PATH', defaultValue: 'WebApi.Tests/WebApi.Tests.csproj', description: 'Path to Tests project')
    }
    stages {
        
            steps {
                powershell '''
                dotnet restore $ENV:WORKSPACE/$($env:SOLUTION_PATH) --source https://api.nuget.org/v3/index/json
                dotnet build $ENV:WORKSPACE/$($env:SOLUTION_PATH) -p:Configuration=release -v:n
                '''
            }
    }
        
}
